import { readFile } from 'node:fs/promises';
import { parse } from 'yaml';
import assert from 'node:assert/strict';
const update=parse(await readFile('.github/workflows/update-prices.yml','utf8'));
const deploy=parse(await readFile('.github/workflows/deploy.yml','utf8'));
const ci=parse(await readFile('.github/workflows/ci.yml','utf8'));
const performance=parse(await readFile('.github/workflows/update-performance.yml','utf8'));
assert.equal(performance.on.schedule[0].cron,'43 */6 * * *');assert.ok(Object.hasOwn(performance.on,'workflow_dispatch'));
assert.deepEqual(performance.concurrency,update.concurrency);
const performanceSteps=performance.jobs.update.steps as {run?:string;uses?:string;if?:string}[];
assert.ok(performanceSteps.some(s=>s.run==='npm run performance:update -- --apply'));
for(const step of performanceSteps.filter(s=>s.uses?.includes('pages-artifact')||s.uses?.includes('deploy-pages')||s.run?.includes('git commit')))assert.match(step.if??'',/changed == 'true'/);
assert.ok(performanceSteps.some(s=>s.run?.includes('git diff --cached --quiet')));
assert.match(performanceSteps.find(s=>s.run?.startsWith('git push'))?.if??'',/deployment.outcome == 'success'/);
assert.equal(update.on.schedule[0].cron,'17 */6 * * *');assert.ok(update.on.workflow_dispatch);
assert.deepEqual(update.concurrency,{group:'pricing-update','cancel-in-progress':false});assert.equal(deploy.concurrency.group,update.concurrency.group);
const steps=update.jobs.update.steps as {name?:string;run?:string;uses?:string;if?:string}[];
const index=(pattern:string)=>steps.findIndex(s=>`${s.name} ${s.uses} ${s.run}`.includes(pattern));
assert.ok(index('npm run prices:update')>=0);
assert.ok(index('npm run prices:update')<index('Prepare a local data commit'));
assert.ok(index('Prepare a local data commit')<index('actions/deploy-pages@'));
assert.ok(index('actions/deploy-pages@')<index('git push origin'));
assert.match(steps[index('Prepare a local data commit')].if??'',/changed == 'true'/);
assert.match(steps[index('git push origin')].if??'',/deployment.outcome == 'success'/);
assert.ok(steps.some(s=>s.run?.includes('git diff --cached --quiet')));
assert.ok(steps.some(s=>s.name==='Reject a stale checkout before deployment'));
assert.ok(ci.jobs.validate.steps.some((s:{run?:string})=>s.run==='npm test'));
assert.ok(!/gh[oprs]_[A-Za-z0-9]{30,}/.test(JSON.stringify(update)));
console.log('工作流结构校验通过：6 小时调度、手动入口、共享互斥、非空提交条件、验证后部署、部署成功后推送。此检查不代替 GitHub runner 实际执行。');
